### ISSUE TITLE
Question: should the resulting differential co-expression network be directed or undirected ?

### ISSUE THREAD

**Issue by BW15061999** [DavisLaboratory/dcanr#3]
Hi, I am wondering what should the result from **dcNetwork**  be treated, directed or undirected? If it is treated as directed, the resulting network's genes with the highest in-degree and out-degree are different. Or the direction of the network doesn't matter?
Thank you!

**Comment by bhuvad** [comment]
Hi,

Apologies for the delayed response. Directionality of the network depends on the method being used (though most) are meant to infer undirected graphs. You can impose a sense of directionality by including some biological knowledge though. For instance, in our paper, we were interested in exploring interactions between transcription factors (TFs) and all other genes, therefore, we induced a subgraph that only contains edges originating from TFs and landed at non-TF genes. For any other form of analyses, the networks inferred are undirected.

Cheers,
Dharmesh
