### ISSUE TITLE
export dcnet to a list of edges

### ISSUE THREAD

**Issue by michelegentili93** [DavisLaboratory/dcanr#4]
Hi, great job and package... how can I export dcnet into a tsp file with the list of edges and their score/sign?
Thanks

**Comment by bhuvad** [comment]
Hi,

The resultant graphs from this analysis are of the `igraph` object. You can use functions from this package to manipulate and export graphs. The `igraph::as_data_frame()` function can be used to convert the graph into an edge and node data frame that can then be exported to a tsv format using the `write.table()` function.

Cheers,
Dharmesh
