### ISSUE TITLE
single gene vs all

### ISSUE THREAD

**Issue by michelegentili93** [DavisLaboratory/dcanr#5]
Is it possible to run the correlation of 1 gene versus all, and have at the end like a star network? Is it possible to specify that at the beginning so that it doesn't compute the correlation of the whole gene expression but only of the single gene vs all the others.

**Comment by bhuvad** [comment]
Hi Michele,

You can run this for the z-score method using the new [dcZscore()](https://davislaboratory.github.io/dcanr/reference/dcZscore.html) function. 

Cheers,
Dharmesh
